# wrangler.toml
name = 'parity-daily'
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
